/* automatically generated by rust-bindgen 0.64.0 */
#[link(name = "Cocoa", kind = "framework")]
#[link(name = "OpenGL", kind = "framework")]
#[link(name = "AppKit", kind = "framework")]

extern "C" {
    pub fn mlx_init() -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn mlx_new_window(
        mlx_ptr: *mut ::std::os::raw::c_void,
        size_x: ::std::os::raw::c_int,
        size_y: ::std::os::raw::c_int,
        title: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn mlx_clear_window(
        mlx_ptr: *mut ::std::os::raw::c_void,
        win_ptr: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_pixel_put(
        mlx_ptr: *mut ::std::os::raw::c_void,
        win_ptr: *mut ::std::os::raw::c_void,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        color: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_new_image(
        mlx_ptr: *mut ::std::os::raw::c_void,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn mlx_get_data_addr(
        img_ptr: *mut ::std::os::raw::c_void,
        bits_per_pixel: *mut ::std::os::raw::c_int,
        size_line: *mut ::std::os::raw::c_int,
        endian: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn mlx_put_image_to_window(
        mlx_ptr: *mut ::std::os::raw::c_void,
        win_ptr: *mut ::std::os::raw::c_void,
        img_ptr: *mut ::std::os::raw::c_void,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_get_color_value(
        mlx_ptr: *mut ::std::os::raw::c_void,
        color: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn mlx_mouse_hook(
        win_ptr: *mut ::std::os::raw::c_void,
        funct_ptr: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
        param: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_key_hook(
        win_ptr: *mut ::std::os::raw::c_void,
        funct_ptr: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
        param: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_expose_hook(
        win_ptr: *mut ::std::os::raw::c_void,
        funct_ptr: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
        param: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_loop_hook(
        mlx_ptr: *mut ::std::os::raw::c_void,
        funct_ptr: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
        param: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_loop(mlx_ptr: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_string_put(
        mlx_ptr: *mut ::std::os::raw::c_void,
        win_ptr: *mut ::std::os::raw::c_void,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        color: ::std::os::raw::c_int,
        string: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_xpm_to_image(
        mlx_ptr: *mut ::std::os::raw::c_void,
        xpm_data: *mut *mut ::std::os::raw::c_char,
        width: *mut ::std::os::raw::c_int,
        height: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn mlx_xpm_file_to_image(
        mlx_ptr: *mut ::std::os::raw::c_void,
        filename: *mut ::std::os::raw::c_char,
        width: *mut ::std::os::raw::c_int,
        height: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn mlx_png_file_to_image(
        mlx_ptr: *mut ::std::os::raw::c_void,
        file: *mut ::std::os::raw::c_char,
        width: *mut ::std::os::raw::c_int,
        height: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn mlx_destroy_window(
        mlx_ptr: *mut ::std::os::raw::c_void,
        win_ptr: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_destroy_image(
        mlx_ptr: *mut ::std::os::raw::c_void,
        img_ptr: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_hook(
        win_ptr: *mut ::std::os::raw::c_void,
        x_event: ::std::os::raw::c_int,
        x_mask: ::std::os::raw::c_int,
        funct: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
        param: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_mouse_hide() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_mouse_show() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_mouse_move(
        win_ptr: *mut ::std::os::raw::c_void,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_mouse_get_pos(
        win_ptr: *mut ::std::os::raw::c_void,
        x: *mut ::std::os::raw::c_int,
        y: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_do_key_autorepeatoff(mlx_ptr: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_do_key_autorepeaton(mlx_ptr: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mlx_do_sync(mlx_ptr: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
